# -*- coding: utf-8 -*-
"""Shipscheduling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZZeoftpnnR1Juouyd1MRO6T5rBdNdWQv
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Load your dataset
df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/AISData.csv")

# Display basic info
print("Shape of dataset:", df.shape)
print("\nColumns:")
print(df.columns)

# Show the first few rows
df.head()

import pandas as pd

# Load your dataset
df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/AISData.csv")

# Print available columns
print(df.columns.tolist())

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Select relevant features
selected_columns = [
    "Year", "Month", "Week",
    "count_entrance", "numofcall",
    "avgservice_time", "avgwaiting_time",
    "count_entrance_feeder", "numofcall_feeder", "avgservice_time_feed", "avgwaiting_time_feed",
    "count_entrance_intermediate", "numofcall_intermediate", "avgservice_time_intermediate", "avgwaiting_time_intermediate",
    "count_entrance_neopanamax", "numofcall_neopanamax", "avgservice_time_neopanamax", "avgwaiting_time_neopanamax",
    "share_neopan"
]

df_filtered = df[selected_columns]

# Display dataset info
print(df_filtered.info())
print(df_filtered.head())

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Drop rows with missing values (you can also use imputation later)
df_filtered.dropna(inplace=True)

# Define features (X) and target (y)
X = df_filtered.drop(columns=["avgwaiting_time"])  # We'll predict avgwaiting_time
y = df_filtered["avgwaiting_time"]

# Split into train and test (80-20 split)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Preprocessing done! Shapes:")
print("X_train:", X_train_scaled.shape)
print("y_train:", y_train.shape)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Initialize model
model = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model
model.fit(X_train_scaled, y_train)

# Predict
y_pred = model.predict(X_test_scaled)

# Evaluation
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"✅ Random Forest Regressor Results:")
print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"R² Score: {r2:.2f}")

import matplotlib.pyplot as plt
import seaborn as sns

# Get feature importances
importances = model.feature_importances_
feature_names = X.columns

# Sort and plot
indices = importances.argsort()[::-1]
plt.figure(figsize=(12, 6))
sns.barplot(x=importances[indices], y=feature_names[indices], palette="viridis")
plt.title("📊 Feature Importances - What Affects Waiting Time")
plt.xlabel("Importance Score")
plt.ylabel("Features")
plt.tight_layout()
plt.show()

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

# Define hyperparameter grid
param_grid = {
    'n_estimators': [50, 100, 200],  # Number of trees
    'max_depth': [None, 10, 20],  # Depth of each tree
    'min_samples_split': [2, 5, 10],  # Min samples to split a node
    'min_samples_leaf': [1, 2, 4]  # Min samples in a leaf node
}

# Initialize model
rf = RandomForestRegressor(random_state=42)

# Set up GridSearchCV
grid_search = GridSearchCV(
    rf, param_grid, cv=5, scoring='neg_mean_absolute_error', n_jobs=-1, verbose=2
)

# Fit to training data
grid_search.fit(X_train, y_train)

# Get best parameters
best_params = grid_search.best_params_
print("Best Hyperparameters:", best_params)

# Train final model with best params
best_rf = RandomForestRegressor(**best_params, random_state=42)
best_rf.fit(X_train, y_train)

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Predictions on test data
y_pred = best_rf.predict(X_test)

# Calculate metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MAE: {mae}")
print(f"MSE: {mse}")
print(f"R² Score: {r2}")

# Avoid divide-by-zero
df_filtered['congestion_ratio'] = df_filtered['avgwaiting_time'] / (df_filtered['numofcall'] + 1)

# Define simple seasons: Winter(12-2), Summer(3-6), Monsoon(7-9), Autumn(10-11)
def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5, 6]:
        return 'Summer'
    elif month in [7, 8, 9]:
        return 'Monsoon'
    else:
        return 'Autumn'

df_filtered['season'] = df_filtered['Month'].apply(lambda x: get_season(int(x)))

df_filtered = pd.get_dummies(df_filtered, columns=['season'], drop_first=True)

# Example: Mark weeks 1-4 of each month as peak shipping season (dummy logic)
df_filtered['is_peak_week'] = df_filtered['Week'].apply(lambda x: 1 if x <= 4 else 0)

print(df_filtered.columns)

# Drop rows with any missing values (if any)
df_filtered.dropna(inplace=True)

# Define X and y
X = df_filtered.drop(columns=['avgwaiting_time'])  # Target is overall waiting time
y = df_filtered['avgwaiting_time']

# Train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train using best hyperparameters from earlier
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=200, random_state=42)
rf.fit(X_train, y_train)

# Evaluate
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
y_pred = rf.predict(X_test)

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("🎯 Model with Feature Engineering:")
print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"R² Score: {r2:.2f}")

def predict_wait_time(model, input_data):
    """
    Predicts avg waiting time given input features as a dictionary.

    Params:
    - model: trained RandomForestRegressor
    - input_data: dict with all feature names as keys

    Returns:
    - predicted waiting time (float)
    """
    import pandas as pd

    # Convert dict to DataFrame
    input_df = pd.DataFrame([input_data])

    # Predict
    prediction = model.predict(input_df)[0]
    return round(prediction, 2)

sample_input = {
    'Year': 2025,
    'Month': 4,
    'Week': 15,
    'count_entrance': 120,
    'numofcall': 180,
    'avgservice_time': 35,

    'count_entrance_feeder': 40,
    'numofcall_feeder': 60,
    'avgservice_time_feed': 28,
    'avgwaiting_time_feed': 7,

    'count_entrance_intermediate': 30,
    'numofcall_intermediate': 45,
    'avgservice_time_intermediate': 30,
    'avgwaiting_time_intermediate': 5,

    'count_entrance_neopanamax': 25,
    'numofcall_neopanamax': 35,
    'avgservice_time_neopanamax': 33,
    'avgwaiting_time_neopanamax': 6,

    'share_neopan': 26,
    'congestion_ratio': 1.2,

    'season_Monsoon': 0,
    'season_Summer': 1,
    'season_Winter': 0,
    'is_peak_week': 1
}

predicted_time = predict_wait_time(rf, sample_input)
print(f"🚢 Predicted Avg Waiting Time: {predicted_time} hours")

# If you already split your data like this:
from sklearn.model_selection import train_test_split

# Assuming 'df_filtered' contains the engineered features:
# Assuming 'df_filtered' contains the engineered features:
feature_cols = ['count_entrance', 'numofcall', 'avgservice_time', 'avgwaiting_time',
                'share_neopan', 'congestion_ratio', 'is_peak_week',
                'season_Monsoon', 'season_Summer', 'season_Winter',
                'count_entrance_feeder', 'numofcall_feeder', 'avgservice_time_feed', 'avgwaiting_time_feed',
                'count_entrance_intermediate', 'numofcall_intermediate', 'avgservice_time_intermediate', 'avgwaiting_time_intermediate',
                'count_entrance_neopanamax'
               ]  # Updated to include all relevant features

X = df_filtered[feature_cols]        # Use df_filtered here
y = df_filtered['avgwaiting_time']   # Actual waiting time (target)

# Splitting data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Get predictions on the test set
y_pred = model.predict(X_test)

# True values from test set
y_true = y_test.values

# Ensure X_test has the same columns as used during training

# Now you can get predictions
y_pred = model.predict(X_test)
y_true = y_test.values

# Get predictions now (should work fine)
y_pred = model.predict(X_test)
y_true = y_test.values

from sklearn.metrics import fbeta_score

# Binary conversion (e.g., > 24 hrs = delay)
y_true_binary = (y_true > 24).astype(int)
y_pred_binary = (y_pred > 24).astype(int)

f1 = fbeta_score(y_true_binary, y_pred_binary, beta=1)
f2 = fbeta_score(y_true_binary, y_pred_binary, beta=2)
f3 = fbeta_score(y_true_binary, y_pred_binary, beta=3)

print(f"F1 Score: {f1:.2f}")
print(f"F2 Score: {f2:.2f}")
print(f"F3 Score: {f3:.2f}")

import seaborn as sns
import matplotlib.pyplot as plt

# Instead of 'df', use 'df_filtered' which contains engineered features
plt.figure(figsize=(12, 8))
sns.heatmap(df_filtered[feature_cols + ['avgwaiting_time']].corr(), annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Feature Correlation with Avg Waiting Time")
plt.show()

plt.figure(figsize=(8, 6))
plt.scatter(y_test, y_pred, alpha=0.6, color='teal')
plt.xlabel("Actual Waiting Time")
plt.ylabel("Predicted Waiting Time")
plt.title("Actual vs Predicted Waiting Time")
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')
plt.grid(True)
plt.show()

errors = y_test - y_pred

plt.figure(figsize=(8, 5))
sns.histplot(errors, kde=True, bins=30, color='orange')
plt.title("Distribution of Prediction Errors")
plt.xlabel("Error (Actual - Predicted)")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(12, 6))
sns.barplot(data=df, x='Port', y='avgwaiting_time', ci=None)
plt.title("Average Waiting Time by Port")
plt.ylabel("Avg Waiting Time (hours)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np

def schedule_ships(model, ship_data):
    """
    Schedules ships optimally based on predicted waiting times.

    Params:
    - model: Trained ML model (RandomForestRegressor)
    - ship_data: List of dictionaries with ship details

    Returns:
    - Optimized schedule (DataFrame)
    """

    # Convert input data to DataFrame
    df_ships = pd.DataFrame(ship_data)

    # Predict waiting time for each ship
    df_ships['Predicted_Waiting_Time'] = df_ships.apply(lambda x: model.predict(pd.DataFrame([x.drop('Ship_ID')]))[0], axis=1)

    # Sort ships based on Shortest Job First (SJF) scheduling
    df_ships = df_ships.sort_values(by=['Predicted_Waiting_Time'])

    # Assign docking times
    current_time = 0
    schedule = []

    for _, row in df_ships.iterrows():
        ship_id = row['Ship_ID']
        arrival_time = row['Arrival_Time']
        service_time = row['Service_Time']

        # Ensure ship is docked at or after its arrival time
        start_time = max(current_time, arrival_time)
        end_time = start_time + service_time

        # Store schedule
        schedule.append({
            'Ship_ID': ship_id,
            'Start_Time': start_time,
            'End_Time': end_time,
            'Predicted_Waiting_Time': row['Predicted_Waiting_Time']
        })

        # Update current time
        current_time = end_time

    # Convert to DataFrame
    df_schedule = pd.DataFrame(schedule)

    return df_schedule

# Example Usage
ship_data = [
    {'Ship_ID': 'S1', 'Arrival_Time': 2, 'Service_Time': 4, 'Feature1': 10, 'Feature2': 20},
    {'Ship_ID': 'S2', 'Arrival_Time': 1, 'Service_Time': 3, 'Feature1': 12, 'Feature2': 18},
    {'Ship_ID': 'S3', 'Arrival_Time': 5, 'Service_Time': 2, 'Feature1': 15, 'Feature2': 25},
]

# Call function with trained model (Replace `rf_model` with your actual model)
# optimized_schedule = schedule_ships(rf_model, ship_data)
# print(optimized_schedule)

import numpy as np
import random
import pandas as pd

# Objective function: Calculate total waiting time for a given ship order
def calculate_total_waiting_time(ship_order, ships):
    current_time = 0
    total_waiting_time = 0

    for ship_id in ship_order:
        ship = ships[ship_id]
        arrival_time = ship['Arrival_Time']
        service_time = ship['Service_Time']

        # Ship can only start after it arrives
        start_time = max(current_time, arrival_time)
        waiting_time = start_time - arrival_time

        # Add waiting time to total
        total_waiting_time += waiting_time
        current_time = start_time + service_time  # Update time after ship leaves

    return total_waiting_time

# Generate initial population (random ship orders)
def generate_population(ships, size=10):
    population = []
    ship_ids = list(ships.keys())

    for _ in range(size):
        random.shuffle(ship_ids)  # Shuffle ship order randomly
        population.append(ship_ids.copy())

    return population

# Selection: Choose the best schedules (lowest waiting time)
def select_best(population, ships, top_k=5):
    sorted_population = sorted(population, key=lambda order: calculate_total_waiting_time(order, ships))
    return sorted_population[:top_k]  # Return top best solutions

# Crossover: Mix two schedules to create a new one
def crossover(parent1, parent2):
    size = len(parent1)
    child = [-1] * size

    # Select a crossover point
    crossover_point = random.randint(1, size - 2)

    # Copy first part from parent1
    child[:crossover_point] = parent1[:crossover_point]

    # Fill remaining slots with ships from parent2 (in order)
    remaining_ships = [ship for ship in parent2 if ship not in child]
    child[crossover_point:] = remaining_ships

    return child

# Mutation: Swap two ships randomly
def mutate(schedule):
    idx1, idx2 = random.sample(range(len(schedule)), 2)
    schedule[idx1], schedule[idx2] = schedule[idx2], schedule[idx1]
    return schedule

# Genetic Algorithm to optimize ship scheduling
def genetic_algorithm(ships, generations=50, population_size=10):
    population = generate_population(ships, population_size)

    for _ in range(generations):
        best_schedules = select_best(population, ships)  # Select best
        new_population = best_schedules.copy()

        # Create new offspring
        while len(new_population) < population_size:
            parent1, parent2 = random.sample(best_schedules, 2)
            child = crossover(parent1, parent2)
            if random.random() < 0.2:  # Mutation chance 20%
                child = mutate(child)
            new_population.append(child)

        population = new_population  # Update population

    # Return the best schedule
    best_schedule = select_best(population, ships)[0]
    return best_schedule, calculate_total_waiting_time(best_schedule, ships)

# Example Ship Data
ships = {
    'S1': {'Arrival_Time': 2, 'Service_Time': 4},
    'S2': {'Arrival_Time': 1, 'Service_Time': 3},
    'S3': {'Arrival_Time': 5, 'Service_Time': 2},
    'S4': {'Arrival_Time': 3, 'Service_Time': 5},
    'S5': {'Arrival_Time': 4, 'Service_Time': 3},
}

# Run Genetic Algorithm for scheduling
best_schedule, best_wait_time = genetic_algorithm(ships)

# Print results
print("🚢 Optimized Ship Schedule:", best_schedule)
print("⏳ Minimum Total Waiting Time:", best_wait_time)

"""2nd model

"""

# Remove leading/trailing spaces from column names
df.columns = df.columns.str.strip()

df.drop(['Port', 'country'], axis=1, inplace=True)

df.dropna(inplace=True)
print("Shape after dropping NA:", df.shape)

# Normalize selected features
from sklearn.preprocessing import MinMaxScaler

priority_features = ['avgwaiting_time', 'count_entrance', 'avgservice_time']
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df[priority_features])
df_scaled = pd.DataFrame(df_scaled, columns=[f"{col}_norm" for col in priority_features])

# Add normalized features back
df = pd.concat([df.reset_index(drop=True), df_scaled], axis=1)

# Create a weighted priority score
df['priority_score'] = (
    0.5 * df['avgwaiting_time_norm'] +
    0.3 * df['count_entrance_norm'] +
    0.2 * df['avgservice_time_norm']
)

df_sorted = df.sort_values(by='priority_score', ascending=False)
df_sorted[['Year', 'Week', 'avgwaiting_time', 'priority_score']].head(10)

selected_columns = [
    'Year', 'Month', 'Week',
    'count_entrance', 'numofcall', 'avgservice_time', 'avgwaiting_time',
    'count_entrance_feeder', 'numofcall_feeder', 'avgservice_time_feed', 'avgwaiting_time_feed',
    'count_entrance_intermediate', 'numofcall_intermediate', 'avgservice_time_intermediate', 'avgwaiting_time_intermediate', # Removed extra spaces here
    'count_entrance_neopanamax', 'numofcall_neopanamax', 'avgservice_time_neopanamax', 'avgwaiting_time_neopanamax',
    'share_neopan'
]
df = df[selected_columns]

# Clean column names
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

# Drop rows with missing data (for now)
df.dropna(inplace=True)

print(f"Remaining rows after dropna: {df.shape[0]}")

# Create Congestion Ratio
df['congestion_ratio'] = df['count_entrance'] / df['numofcall']

# Create Priority Score (Weighted sum of features)
df['priority_score'] = (
    0.3 * df['avgwaiting_time'] +
    0.3 * df['avgservice_time'] +
    0.2 * df['count_entrance'] +
    0.2 * df['numofcall']
)

print("✅ Feature Engineering done! Columns now include congestion_ratio and priority_score.")
df[['congestion_ratio', 'priority_score']].head()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Define Features and Target
features = ['avgwaiting_time', 'avgservice_time', 'count_entrance', 'numofcall', 'congestion_ratio']
X = df[features]
y = df['priority_score']

# Split Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("🎯 Model Performance:")
print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"R² Score: {r2:.2f}")

def schedule_ships(model, ship_data_df):
    """
    Schedules ships by predicting their priority score and sorting.

    Params:
    - model: trained regression model
    - ship_data_df: DataFrame containing new ship data with same features used in training

    Returns:
    - DataFrame sorted by priority_score (descending)
    """
    import pandas as pd

    # Predict priority score
    ship_data_df = ship_data_df.copy()
    ship_data_df['predicted_priority'] = model.predict(ship_data_df)

    # Sort by priority
    scheduled_df = ship_data_df.sort_values(by='predicted_priority', ascending=False)

    return scheduled_df

import pandas as pd

# Manually entering data for 3 ships
manual_data = [
    {
        'count_entrance': 80,
        'numofcall': 120,
        'avgservice_time': 50,
        'avgwaiting_time': 12,
        'share_neopan': 15,
        'congestion_ratio': 80/120  # = 0.6667
    },
    {
        'count_entrance': 95,
        'numofcall': 100,
        'avgservice_time': 60,
        'avgwaiting_time': 10,
        'share_neopan': 30,
        'congestion_ratio': 95/100  # = 0.95
    },
    {
        'count_entrance': 60,
        'numofcall': 90,
        'avgservice_time': 45,
        'avgwaiting_time': 15,
        'share_neopan': 20,
        'congestion_ratio': 60/90  # = 0.6667
    }
]

# Convert to DataFrame
incoming_ships_df = pd.DataFrame(manual_data)
incoming_ships_df

trained_model = model

feature_columns = X.columns.tolist()  # X is your training data

scheduled_ships = schedule_ships(trained_model, incoming_ships_df[feature_columns])

scheduled_ships[['count_entrance', 'numofcall', 'predicted_priority']]

scheduled_ships = scheduled_ships.sort_values(by='predicted_priority', ascending=False)
print(scheduled_ships)

import pandas as pd

# Load the data

df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/AISData.csv")
# Drop rows with nulls in important columns
important_cols = ['count_entrance', 'numofcall', 'avgservice_time']
df = df.dropna(subset=important_cols)

# Create congestion ratio
df['congestion_ratio'] = df['count_entrance'] / df['numofcall']

# Create priority score (manual weighted sum OR predicted target)
df['priority_score'] = (
    0.4 * df['count_entrance'] +
    0.3 * df['numofcall'] +
    0.3 * df['congestion_ratio'] * 100
)

# Keep only relevant columns for now
features = ['count_entrance', 'numofcall', 'congestion_ratio']
target = 'priority_score'
X = df[features]
y = df[target]

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

# Train the model
model = RandomForestRegressor(n_estimators=200, random_state=42)
model.fit(X_train, y_train)

# Evaluate
y_pred = model.predict(X_test)
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))

def schedule_ships(trained_model, incoming_df):
    # Predict priority
    incoming_df['predicted_priority'] = trained_model.predict(incoming_df)
    return incoming_df.sort_values(by='predicted_priority', ascending=False)

incoming_ships_data = [
    {'count_entrance': 80, 'numofcall': 120, 'congestion_ratio': 80/120},
    {'count_entrance': 95, 'numofcall': 100, 'congestion_ratio': 95/100},
    {'count_entrance': 60, 'numofcall': 90, 'congestion_ratio': 60/90},
]

incoming_df = pd.DataFrame(incoming_ships_data)
scheduled = schedule_ships(model, incoming_df)

# See the berthing order
scheduled[['count_entrance', 'numofcall', 'predicted_priority']]

"""# Add more features"""

import pandas as pd

# Load your dataset (update the path if needed)
df = pd.read_csv("/content/drive/My Drive/Colab Notebooks/AISData.csv")

# Drop rows with missing values
df.dropna(inplace=True)

# Feature Engineering
df['congestion_ratio'] = df['count_entrance'] / df['numofcall']
df['priority_score'] = (
    0.25 * df['count_entrance'] +
    0.25 * df['numofcall'] +
    0.15 * df['avgservice_time'] +
    0.15 * df['avgwaiting_time'] +
    0.2 * df['share_neopan']
)

# Selected features for model input
selected_features = [
    'count_entrance', 'numofcall', 'avgservice_time', 'avgwaiting_time',
    'avgservice_time_feed', 'avgwaiting_time_feed',
    'avgservice_time_neopanamax', 'avgwaiting_time_neopanamax',
    'share_neopan'
]

X = df[selected_features]
y = df['priority_score']

print("Shape of Features:", X.shape)
print("Shape of Target:", y.shape)

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import train_test_split

# Assuming X and y are already defined
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluation metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("MAE:", round(mae, 2)) //mean absolute error lower= better
print("MSE:", round(mse, 2)) // mean square error  lower= better
print("R² Score:", round(r2, 2))  0-1 prediction best  is 1 // f1 is harmonic mean of precision and recall

import pandas as pd

def schedule_ships(model, incoming_data):
    """
    Schedule ships based on predicted priority score.

    Parameters:
    - model: trained machine learning model
    - incoming_data: list of dictionaries, each dict contains input features

    Returns:
    - DataFrame of ships sorted by predicted priority (descending)
    """
    # Convert to DataFrame
    df_incoming = pd.DataFrame(incoming_data)

    # Predict priority score
    df_incoming['predicted_priority'] = model.predict(df_incoming)

    # Sort by predicted priority (descending)
    df_sorted = df_incoming.sort_values(by='predicted_priority', ascending=False).reset_index(drop=True)

    return df_sorted

feature_columns = X.columns.tolist()
import joblib
joblib.dump(feature_columns, "feature_columns.pkl")
joblib.dump(model, "ship_priority_model.pkl")

def schedule_ships(model, incoming_data, feature_columns):
    df_incoming = pd.DataFrame(incoming_data)

    # Ensure all training features exist
    for col in feature_columns:
        if col not in df_incoming.columns:
            df_incoming[col] = 0  # fill missing with 0

    # Reorder columns to match training
    df_incoming = df_incoming[feature_columns]

    # Predict priority
    df_incoming['predicted_priority'] = model.predict(df_incoming)

    # Sort by priority
    return df_incoming.sort_values(by='predicted_priority', ascending=False).reset_index(drop=True)

model = joblib.load("ship_priority_model.pkl")
feature_columns = joblib.load("feature_columns.pkl")

# same incoming_ships as before
scheduled_df = schedule_ships(model, incoming_ships_data, feature_columns)
scheduled_df[['count_entrance', 'numofcall', 'predicted_priority']]

#visulasiation and f1 f2 f3

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, f1_score, classification_report, precision_recall_fscore_support

# -------------------------------
# 🔍 REGRESSION VISUALIZATION
# -------------------------------
y_true = y_test
y_pred = model.predict(X_test)

# 📈 Actual vs Predicted
plt.figure(figsize=(8,5))
sns.scatterplot(x=y_true, y=y_pred)
plt.plot([y_true.min(), y_true.max()], [y_true.min(), y_true.max()], color='red', linestyle='--')
plt.xlabel("Actual Priority")
plt.ylabel("Predicted Priority")
plt.title("Actual vs Predicted Priority Score")
plt.grid(True)
plt.show()

# 📊 Residual Plot
residuals = y_true - y_pred
plt.figure(figsize=(8,5))
sns.histplot(residuals, bins=30, kde=True)
plt.title("Residual Distribution")
plt.xlabel("Prediction Error")
plt.ylabel("Frequency")
plt.grid(True)
plt.show()

# -------------------------------
# 💡 FEATURE IMPORTANCE
# -------------------------------
importances = model.feature_importances_
feat_df = pd.DataFrame({'Feature': X.columns, 'Importance': importances})
feat_df = feat_df.sort_values(by='Importance', ascending=False)

plt.figure(figsize=(10,6))
sns.barplot(data=feat_df.head(15), x='Importance', y='Feature', palette='coolwarm')
plt.title("Top 15 Feature Importances")
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.grid(True)
plt.show()

# 🎯 Bin targets into 3 classes: Low (0), Medium (1), High (2)
def bin_priority(score):
    if score < 60:
        return 0  # Low
    elif score < 80:
        return 1  # Medium
    else:
        return 2  # High

y_true_class = y_true.apply(bin_priority)
y_pred_class = pd.Series(y_pred).apply(bin_priority)

# 📋 Classification Report
print("📋 Classification Report:")
print(classification_report(y_true_class, y_pred_class, target_names=["Low", "Medium", "High"]))

# 🧠 Fβ scores
prec, recall, fbeta, _ = precision_recall_fscore_support(y_true_class, y_pred_class, beta=2, average='macro')
print(f"🎯 F2 Score: {fbeta:.2f}")